format = """
$all $fill ${status}${cmd_duration}${custom.proxy_enable}${custom.proxy_disable}\n$character
"""

#right_format = """
#"""

add_newline = true
follow_symlinks = true

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](yellow)"
vimcmd_symbol = "[❮](cyan)"

[fill]
symbol = ""
style = "bold #4c566a"


[line_break]
disabled = true

[directory]
truncate_to_repo = false

[package]
disabled = true

[status]
disabled = false
symbol = " "
not_executable_symbol = " "
not_found_symbol = "󱧸 "
sigint_symbol = " "
signal_symbol = " "

[custom.proxy_enable]
format = "[](#F6B17A) "
when = """
if [ -z "${ALL_PROXY}" ] && [ -z "${all_proxy}" ] && [ -z "${HTTP_PROXY}" ] && [ -z "${http_proxy}" ] && [ -z "${HTTPS_PROXY}" ] && [ -z "${https_proxy}" ]; then
  false
else 
  true
fi
"""

[custom.proxy_disable]
format = "[](#7077A1) "
when = """
if [ -z "${ALL_PROXY}" ] && [ -z "${all_proxy}" ] && [ -z "${HTTP_PROXY}" ] && [ -z "${http_proxy}" ] && [ -z "${HTTPS_PROXY}" ] && [ -z "${https_proxy}" ]; then
  true
else 
  false
fi
"""
